### ISSUE TITLE
Does not open in Excel

### ISSUE THREAD

**Issue by dkpinn** [Muyoouu/vba-xero-api#1]
After downloading the file and trying to open it in Excel there is a message from Xero saying that the file extension is incorrect or the file is corrupt.
![Uploading Screenshot_3.png…]()

**Comment by Muyoouu** [comment]
> After downloading the file and trying to open it in Excel there is a message from Xero saying that the file extension is incorrect or the file is corrupt.
Uploading Screenshot_3.png…

Hello @dkpinn, I'm unable to view the screenshot you've uploaded. It appears the image is broken or didn't upload correctly. Could you please try uploading it again? I'm particularly interested in seeing the error message you encountered.

For reference, here's how the broken image appears on my end:
![image](https://github.com/user-attachments/assets/1e59c1fd-f7e6-4fc2-861e-29f2744adac2)

**Comment by dkpinn** [comment]
Hey Musa

 

No problem. I’ve attached it to this mail.

**Comment by Muyoouu** [comment]
Hi, I still can't see the image. This might be because the email reply goes
through a GitHub bot email account and doesn't reach me directly. You might
need to go to the GitHub repo issue page and repost it there. It would also
be helpful if you could add more info about the error. As a disclaimer,
while I'd like to help, I might not be able to solve the problem. I really
appreciate your effort in reporting this issue. Thank you!
